### ISSUE TITLE
audio in demo broken

### ISSUE THREAD

**Issue by ichpuchtli** [whichlight/dancey-dots#3]
`_x` is undefined sometimes causing an error when you try to set the frequency value. I'm not sure if this is the root cause.

```js
function prepSynths(){
  var oscillator = context.createOscillator();
  oscillator.type=1;
  oscillator.frequency.value=_x; // Uncaught TypeError: Failed to set the 'value' property on 'AudioParam': The provided float value is non-finite.
```

**Comment by whichlight** [comment]
hey thanks for the note! yes - i think the web audio api changed, i'll look into it. glad you're digging into the project, what are you making?

**Comment by ichpuchtli** [comment]
I think dancey dots is a really fun and interactive way to show the power of web sockets. I want to use it show some colleagues what the web can do these days. I'll look into it as well. Love you work. 

btw your projects page is broken on your blog
http://whichlight.com/category/projects/
```
Warning: mysql_connect(): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (111) in /var/www/wp-includes/wp-db.php on line 1409
```

**Comment by ichpuchtli** [comment]
hey @whichlight did you get a chance to look at this pull request I made
